'use client';

import React, { useEffect } from 'react';
import { Inter } from 'next/font/google';
// import type { Metadata } from 'next';
import { QuotesProvider } from '@/context/QuotesContext';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// const metadata: Metadata = {
//   title: 'Taller de herraría "El Pariente"',
//   description: 'Generated by create next app',
// };

function RootLayout({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    if (typeof window !== 'undefined') {
      // Your client-side code that uses window goes here
    }
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <QuotesProvider>{children}</QuotesProvider>
      </body>
    </html>
  );
}

export default RootLayout;
